site_name: Processing.py lernen
theme: readthedocs

pages:
- Home: "index.md"
- Sierpinksi-Dreieck: "sierpinski.md"
- Feather Fractal: "feather.md"
- Butterfly Curve: "butterfly.md"
- Lorenz Attratkor: "lorenz.md"
- Kreise und Ellipsen: "foryoureyesonly.md"
- Das with-Statement: "with.md"
- Cantor-Käse: "cantor.md"
- Pythagoras-Baum: "pythagoras.md"
- Text: "text.md"
- Rentenuhr: "rentenuhr.md"
- Hallo Hörnchen: "hallohoernchen.md"
- Moving Kitty: "movingkitty.md"
- Klasse Kitty!: "klassekitty.md"
- Cute Planet: "cuteplanet.md"
- Fluffy Planet 1: "fluffyplanet01.md"
- Running Orc 1: "runningorc.md"
- Running Orc 2: "runningorc4dir.md"
- Running Orc 3: "runningorc3.md"
- Running Orc 4: "runningorc4.md"
- Running Orc 5: "runningorc5.md"
- Running Orc 6: "runningorc6.md"
- Exkurs Rauhnächte: "rauhnaechte.md"
- Walking Pingus: "walkingpingus.md"
- Impressum: "impressum.md"

markdown_extensions:
- footnotes
- admonition

- smarty:
    smart_quotes: False

site_dir: "/Applications/MAMP/htdocs/processingpy"

edit_uri: blob/master/docs

google_analytics: ["UA-89437459-1", "auto"]

repo_url: "https://github.com/kantel/processingpy"

extra_css: [css/user.css]

extra_javascript: ["http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"]

