site_name: Processing.py lernen
theme: readthedocs

pages:
- Home: "index.md"
- Sierpinksi-Dreieck: "sierpinski.md"
- Turmiten: "turmite.md"
- Mandelbrot-Set: "mandelbrot.md"
- Feather Fractal: "feather.md"
- Butterfly Curve: "butterfly.md"
- Lorenz Attratkor: "lorenz.md"
- Kreise und Ellipsen: "foryoureyesonly.md"
- Konfetti: "konfetti.md"
- Das with-Statement: "with.md"
- Cantor-Käse: "cantor.md"
- Drei- und Vierecke: "dreivierecke.md"
- Rechtecke: "sonntagsfrage.md"
- Rosetten-Kurven: "rosetten.md"
- Pythagoras-Baum: "pythagoras.md"
- Text: "text.md"
- Textdateien: "readlines.md"
- Rentenuhr: "rentenuhr.md"
- Bildverarbeitung (1): "tint.md"
- Bildverarbeitung (2): "filter.md"
- Pointillistischer Akt: "farbakt.md"
- Noch mehr Pointillismus: "farbakt2.md"
- Balloons: "balloons.md"
- Shapes: "shapes.md"
- Hallo Hörnchen: "hallohoernchen.md"
- Moving Kitty: "movingkitty.md"
- Klasse Kitty!: "klassekitty.md"
- Cute Planet: "cuteplanet.md"
- Fluffy Planet 1: "fluffyplanet01.md"
- 3D mit Processing.py: "kugel.md"
- Kugeln und Texturen: "kugel02.md"
- Kisten und Texturen: "kiste.md"
- Licht und Schatten: "lights.md"
- Einen Globus basteln: "globen.md"
- OpenWeatherMap: "weather.md"
- WordCram: "wordcram.md"
- Running Orc 1: "runningorc.md"
- Running Orc 2: "runningorc4dir.md"
- Running Orc 3: "runningorc3.md"
- Running Orc 4: "runningorc4.md"
- Running Orc 5: "runningorc5.md"
- Running Orc 6: "runningorc6.md"
- Exkurs Rauhnächte: "rauhnaechte.md"
- Walking Pingus: "walkingpingus.md"
- Impressum: "impressum.md"

markdown_extensions:
- footnotes
- admonition

- smarty:
    smart_quotes: False

site_dir: "/Applications/MAMP/htdocs/processingpy"

edit_uri: blob/master/docs

google_analytics: ["UA-89437459-1", "auto"]

repo_url: "https://github.com/kantel/processingpy"

extra_css: [css/user.css]

extra_javascript: ["http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"]

